import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Priority from "../components/priorityField";
import Filter from "../components/filter";
import { useState } from "react";

const Home: NextPage = () => {
  const [filters, setFilters] = useState<number[]>([0]);
  const [count, setCount] = useState(1);

  const addFilter = () => {
    setCount((prevCount) => prevCount + 1);
    filters.push(count);
    setFilters(filters);
  };

  const clearFilters = () => {
    setCount(1);
    setFilters([0]);
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center bg-slate-50 text-gray-700">
        <div className="w-1/2 min-w-max rounded-lg bg-white p-8 shadow">
          <h1 className="mb-4 text-3xl font-bold text-black">Filters</h1>
          {filters.map((filter) => {
            console.log(filter);

            return (
              <div key={filter} className="mb-2 flex items-center gap-2">
                {filter === 0 ? (
                  <label>Where</label>
                ) : (
                  <label className="bg-gray-200 text-gray-500 px-2 py-1 rounded-lg">AND</label>
                )}
                <Filter />
              </div>
            );
          })}
          <div className="flex justify-between">
            <button className="mt-2" onClick={addFilter}>
              <p className="text-gray-600 underline">+ Add filter</p>
            </button>
            <button className="mt-2" onClick={clearFilters}>
              <p className="text-gray-600 underline">Clear all filters</p>
            </button>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
