import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import CloseIcon from "@mui/icons-material/Close";
import Input from "../components/input";
import Group from "../components/group";

const Home: NextPage = () => {
  const [openFilter, setOpenFilter] = useState(true);
  const [filters, setFilters] = useState<(number | [number])[]>([0]);
  const [count, setCount] = useState(1);

  const addFilter = () => {
    setCount((prevCount) => prevCount + 1);
    filters.push(count);
    setFilters(filters);
  };

  const addGroup = () => {
    setCount((prevCout) => prevCout + 1);
    filters.push([0]);
    setFilters(filters);
  };

  const clearFilters = () => {
    setCount(1);
    setFilters([0]);
  };

  return (
    <>
      <Head>
        <title>Filter component</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-auto flex min-h-screen flex-col items-center bg-slate-50 pt-12 text-gray-700">
        {!openFilter ? (
          <button
            className="rounded-full px-4 py-2 font-bold hover:bg-gray-200"
            onClick={() => setOpenFilter(true)}
          >
            Filter
          </button>
        ) : null}
        {openFilter ? (
          <div className="relative w-1/2 min-w-max rounded-lg bg-white p-4 shadow">
            <button
              className="absolute right-4 top-4 rounded-full p-1 hover:bg-gray-200"
              onClick={() => {
                setOpenFilter(false);
                clearFilters();
              }}
            >
              <CloseIcon />
            </button>
            <h1 className="mb-2 text-3xl font-bold text-black">Filters</h1>
            {filters.map((filter, idx) => {
              if (typeof filter === "number")
                return <Input key={idx} filter={filter} />;
              else
                return (
                  <div key={idx} className="flex items-start gap-4 my-1">
                    <select className="mt-4 rounded-lg bg-gray-200 px-1 py-1 text-sm text-gray-500">
                      <option>AND</option>
                      <option>OR</option>
                    </select>
                    <Group />
                  </div>
                );
            })}
            <div className="mt-2 flex justify-between">
              <div>
                <button className="mt-2" onClick={addFilter}>
                  <p className="rounded-full px-2 py-1 text-gray-500 hover:bg-gray-200">
                    + Add filter
                  </p>
                </button>
                <button className="mt-2" onClick={addGroup}>
                  <p className="rounded-full px-2 py-1 text-gray-500 hover:bg-gray-200">
                    + Add group
                  </p>
                </button>
              </div>
              <button className="mt-2" onClick={clearFilters}>
                <p className="rounded-full px-2 py-1 text-gray-500 hover:bg-gray-200">
                  Clear all filters
                </p>
              </button>
            </div>
          </div>
        ) : null}
      </main>
    </>
  );
};

export default Home;
